soft98/Areas/Admin/Controllers/MatlabController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using soft98.Core.Interface;
using soft98.DataAccessLayer.Entities;

namespace soft98.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class MatlabController : Controller
    {
        
        private IAdminRepository _adminRepository;
        public MatlabController(IAdminRepository adminRepository)
        {
            _adminRepository = adminRepository;
        }
        public async Task<IActionResult> Index()
        {
            var matlabs =await _adminRepository.ShowMatlabs();

            return View(matlabs);
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Matlab matlab)
        {
            if (ModelState.IsValid)
            {
                var newMatlab = new Matlab()
                {
                    Title = matlab.Title,
                    Description = matlab.Description,
                    Date = PersianDateTime.Now.ToString("yyyy/MM/dd"),
                    Show = matlab.Show,
                    NumberSeen = 0,
                    IsSoft = matlab.IsSoft,
                    IsMobile = matlab.IsMobile,
                    IsTech = matlab.IsTech
                };

                await _adminRepository.AddMatlab(newMatlab);
                await _adminRepository.SaveChanges();

                return RedirectToAction("Index");
            }
            else
            {
                return View(matlab);
            }
        }

        public async Task<IActionResult> Edite(int id)
        {
            var matlab = await _adminRepository.ShowMatlabbyId(id);
            return View(matlab);
        }

        [HttpPost]
        public async Task<IActionResult> Edite(int id, Matlab matlab)
        {
            if (ModelState.IsValid)
            {
                var res = await _adminRepository.UpdateMatlab(id, matlab.Title, matlab.Description, matlab.Show,
                    matlab.IsSoft, matlab.IsMobile, matlab.IsTech);

                if (res)
                {
                    await _adminRepository.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            return View(id);
        }

        public  IActionResult  Delete(int? id)
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var res=  await _adminRepository.DeleteMatlab(id);
            if (res)
            {
                await _adminRepository.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();

        }

        public async Task<IActionResult> Details(int id)
        {
           var matlab = await _adminRepository.ShowMatlabbyId(id);
           return View(matlab);
        }

    }
}

soft98/Areas/Admin/Views/Matlab/Create.cshtml
@model soft98.DataAccessLayer.Entities.Matlab

@{
    ViewData["Title"] = "ایجاد مطلب";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12
     col-sm-offset-0 col-xs-12 col-xs-offset-0" style="margin-top: 50px;">
    <h3 class="pull-right title-h">ایجاد مطلب</h3>
    <h3 class="pull-left">
        <a asp-action="Index" class="btn-orange">بازگشت</a>
    </h3>
</div>
<div class="clearfix"></div>
<br />

<div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12
     col-sm-offset-0 col-xs-12 col-xs-offset-0">
    <form asp-action="Create" class="table-chart" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Title" class="control-label labelStyle"></label>
            <input asp-for="Title" class="form-control" style="margin-right: 10px; font-size: 17px;" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Description" class="control-label labelStyle"></label>
            <textarea asp-for="Description" class="form-control" style="margin-right: 10px; font-size: 17px;"></textarea>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="form-groupM">
            <div class="containerM" style="color: #dbd8d8">
                @Html.DisplayNameFor(model => model.Show)
                <input type="checkbox" asp-for="Show" >
                <span class="checkmark"> </span><i class="fa fa-check check-btn" ></i>
            </div>
        </div>
        <div class="form-groupM">
            <div class="containerM" style="color: #dbd8d8">
                @Html.DisplayNameFor(model => model.IsSoft)
                <input type="checkbox" asp-for="IsSoft" >
                <span class="checkmark"> </span><i class="fa fa-check check-btn" ></i>
            </div>
        </div>
        <div class="form-groupM">
            <div class="containerM" style="color: #dbd8d8">
                @Html.DisplayNameFor(model => model.IsMobile)
                <input type="checkbox" asp-for="IsMobile" >
                <span class="checkmark"> </span><i class="fa fa-check check-btn" ></i>
            </div>
        </div>
        <div class="form-groupM">
            <div class="containerM" style="color: #dbd8d8">
                @Html.DisplayNameFor(model => model.IsTech)
                <input type="checkbox" asp-for="IsTech" >
                <span class="checkmark"> </span><i class="fa fa-check check-btn" ></i>
            </div>
        </div>
        <div class="form-group">
            <input type="submit" value="ایجاد" class="btn btn-orange" style="width: 20%;margin-right: 40%;"/>
        </div>
    </form>
</div>
 

soft98/Areas/Admin/Views/Matlab/Delete.cshtml
@{
    Layout = null;
    var id= ViewBag.catId;
}

<form  asp-action="Delete" asp-route-catId="id" >
    <div asp-validation-summary="ModelOnly" class="text-center"></div>
    <div class="form-group" style="margin-bottom: 80px !important;">
        <h3 style="color: black;" class="text-center"> آیا از حذف اطمینان دارید؟</h3>
    </div>
    <div class="form-group">
        <input type="submit" class="btn-orangeM pull-right" value="تایید" style="border: none; top: -45px !important;" />
        <a  asp-action="Index"  asp-controller="Matlab" class="btn-orangeM pull-left" style=" top: -45px !important;">بازگشت</a>
    </div>
</form>

soft98/Areas/Admin/Views/Matlab/Details.cshtml
@model soft98.DataAccessLayer.Entities.Matlab

@{
    ViewData["Title"] = "جزئیات مطلب";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12
     col-sm-offset-0 col-xs-12 col-xs-offset-0" style="margin-top: 50px;">
    <h3 class="pull-right title-h">جزئیات مطلب</h3>
    <h3 class="pull-left">
        <a   asp-action="Create" class="btn-orange">ایجاد مطلب</a>
    </h3>
</div>
<div class="clearfix"></div>
<br />

<div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12
     col-sm-offset-0 col-xs-12 col-xs-offset-0" style="margin-right: -135px;">
    <dl class="dl-horizontal table-chart-detail" >
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="text-center">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <hr />
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="text-center">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <hr />
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class="text-center" style="direction: ltr;">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <hr />
        <dt>
            @Html.DisplayNameFor(model => model.Show)
        </dt>
        <dd class="text-center">
            @Html.DisplayFor(model => model.Show)
        </dd>
        <hr />
        <dt>
            @Html.DisplayNameFor(model => model.NumberSeen)
        </dt>
        <dd class="text-center">
            @Html.DisplayFor(model => model.NumberSeen)
        </dd>
        <hr />
        <dt>
            @Html.DisplayNameFor(model => model.IsSoft)
        </dt>
        <dd class="text-center">
            @Html.DisplayFor(model => model.IsSoft)
        </dd>
        <hr />
        <dt>
            @Html.DisplayNameFor(model => model.IsMobile)
        </dt>
        <dd class="text-center">
            @Html.DisplayFor(model => model.IsMobile)
        </dd>
        <hr />
        <dt>
            @Html.DisplayNameFor(model => model.IsTech)
        </dt>
        <dd class="text-center">
            @Html.DisplayFor(model => model.IsTech)
        </dd>
    </dl>
</div>
<div style="display: inline-block; margin-right:260px " class="btn-wrapp">
    <a asp-action="Edite" asp-route-id="@Model.Id" class="btn-orange">تغییر مطلب</a> |
    <a asp-action="Index" class="btn-orange">بازگشت</a>
</div>

soft98/Areas/Admin/Views/Matlab/Edite.cshtml
@model soft98.DataAccessLayer.Entities.Matlab

@{
    ViewData["Title"] = "ویرایش مطلب";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12
     col-sm-offset-0 col-xs-12 col-xs-offset-0" style="margin-top: 50px;">
    <h3 class="pull-right title-h">ویرایش مطلب</h3>
    <h3 class="pull-left">
        <a asp-action="Index" class="btn-orange">بازگشت</a>
    </h3>
</div>
<div class="clearfix"></div>
<br />
<div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12
        col-sm-offset-0 col-xs-12 col-xs-offset-0">
    <form asp-action="Edite" class="table-chart">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label asp-for="Title" class="control-label labelStyle"></label>
            <input asp-for="Title" class="form-control"  style="margin-right: 10px; font-size: 17px;"/>
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Description" class="control-label labelStyle"></label>
            <textarea asp-for="Description" class="form-control" style="margin-right: 10px; font-size: 17px;"></textarea>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="form-group">
            <div class="checkbox" style="color: #dbd8d8">
                <input style="margin-right: 100px"  asp-for="Show" /> @Html.DisplayNameFor(model => model.Show)
            </div>
        </div>
        <div class="form-group">
            <div class="checkbox" style="color: #dbd8d8">
                <input style="margin-right: 100px"  asp-for="IsSoft" /> @Html.DisplayNameFor(model => model.IsSoft)
            </div>
        </div>
        <div class="form-group">
            <div class="checkbox" style="color: #dbd8d8">
                <input style="margin-right: 100px"  asp-for="IsMobile" /> @Html.DisplayNameFor(model => model.IsMobile)
            </div>
        </div>
        <div class="form-group">
            <div class="checkbox" style="color: #dbd8d8">
                <input style="margin-right: 100px"  asp-for="IsTech" /> @Html.DisplayNameFor(model => model.IsTech)
            </div>
        </div>
        <div class="form-group">
            <input type="submit"  value="اعمال تغییرات" class="btn btn-orange" style="width: 20%;margin-right: 40%;" />
        </div>
    </form>
</div>

soft98/Areas/Admin/Views/Matlab/Index.cshtml
@model IEnumerable<soft98.DataAccessLayer.Entities.Matlab>

@{
    ViewData["Title"] = "لیست مطالب";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12
     col-sm-offset-0 col-xs-12 col-xs-offset-0" style="margin-top: 50px;">
    <h3 class="pull-right title-h">نمایش مطالب</h3>
    <h3 class="pull-left">
        <a asp-action="Create" class="btn-orange">ایجاد مطلب </a>
    </h3>
</div>
<div class="clearfix"></div>
<br />

<div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12
     col-sm-offset-0 col-xs-12 col-xs-offset-0" style="margin-right: -135px;">
    <table class="table table-chart-matlab">
        <thead>
            <tr>
                <th style="width: 20%" class="text-center">
                    @Html.DisplayNameFor(model => model.Title)
                </th>

                <th style="width: 10%" class="text-center">
                    @Html.DisplayNameFor(model => model.Show)
                </th>
                <th style="width: 10%" class="text-center">
                    @Html.DisplayNameFor(model => model.NumberSeen)
                </th>
                <th style="width: 7%" class="text-center">
                    @Html.DisplayNameFor(model => model.IsSoft)
                </th>
                <th style="width: 7%" class="text-center">
                    @Html.DisplayNameFor(model => model.IsMobile)
                </th>
                <th style="width: 7%" class="text-center">
                    @Html.DisplayNameFor(model => model.IsTech)
                </th>
                <th style="width: 15%" class="text-center">عملیات</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td style="width: 20%">
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td style="width: 10%">
                        @Html.DisplayFor(modelItem => item.Show)
                    </td>
                    <td style="width: 10%">
                        @Html.DisplayFor(modelItem => item.NumberSeen)
                    </td>
                    <td style="width: 7%">
                        @Html.DisplayFor(modelItem => item.IsSoft)
                    </td>
                    <td style="width: 7%">
                        @Html.DisplayFor(modelItem => item.IsMobile)
                    </td>
                    <td style="width: 7%">
                        <input type="checkbox" checked="@item.IsTech" disabled="disabled"/>
                    </td>
                    <td style="width: 15%">
                        <a asp-action="Edite" asp-route-id="@item.Id" class="btn-xs btn-warning">ویرایش</a> |
                        <a asp-action="Details" asp-route-id="@item.Id" class="btn-xs btn-info">جزئیِات</a> |
                        <a href="#" onclick="DeleteM(@item.Id)" class="btn-xs btn-danger">حذف</a>
                    </td>
                </tr>
            }

        </tbody>
    </table>
</div>

<div id="myModal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="bodymodal" class="modal-body">

            </div>
        </div>

    </div>
</div>

<script>
    function DeleteM(id) {
        $.ajax({
            url: "/Admin/Matlab/Delete/" + id,
            type: "Get",
            data: {}
        }).done(function (result) {
            $('#myModal').modal('show');
            $('#myModalHeader').html('');
            $('#bodymodal').html(result);
        });
    }
</script>