soft98/Areas/Admin/Controllers/BannerController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using soft98.Core.Interface;
using soft98.DataAccessLayer.Entities;
using soft98.DataAccessLayer.Migrations;

namespace soft98.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BannerController : Controller
    {
        private IAdminRepository _adminRepository;

        public BannerController(IAdminRepository adminRepository)
        {
            _adminRepository = adminRepository;
        }

        public async Task<IActionResult> Index()
        {
            var banners = await _adminRepository.ShowBanner();
            return View(banners);
        }
        public async Task<IActionResult> Details(int id)
        {
            var banner = await _adminRepository.ShowBannerById(id);
            return View(banner);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Banner banner)
        {
            if (ModelState.IsValid)
            {
                await _adminRepository.AddBanner(banner);
                await _adminRepository.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(banner);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var banner = await _adminRepository.ShowBannerById(id);
            return View(banner);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, Banner banner)
        {
            if (ModelState.IsValid)
            {
                var res = await _adminRepository.UpdateBanner(id, banner.PlaceCode, banner.Description, banner.Price, banner.IsActive);
                if (res)
                {
                    await _adminRepository.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            return View(banner);
        }

        public IActionResult Delete(int? id)
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var res = await _adminRepository.RemoveBanner(id);
            if (res)
            {
               await _adminRepository.SaveChanges();
               return RedirectToAction("Index");
            }

            return RedirectToAction("index");
        }

      
    }
}

soft98/Areas/Admin/Views/Banner/Create.cshtml
@model soft98.DataAccessLayer.Entities.Banner

@{
    ViewData["Title"] = "ایجاد بنر";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12
     col-sm-offset-0 col-xs-12 col-xs-offset-0" style="margin-top: 50px;">
    <h3 class="pull-right title-h">ایجاد بنر </h3>
    <h3 class="pull-left">
        <a asp-action="Index" class="btn-orange">بازگشت</a>
    </h3>
</div>
<div class="clearfix"></div>
<br />

<div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12
     col-sm-offset-0 col-xs-12 col-xs-offset-0">
    <form asp-action="Create" class="table-chart" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="PlaceCode" class="control-label labelStyle"></label>
            <input asp-for="PlaceCode" class="form-control"  style="margin-right: 10px; font-size: 17px;"  />
            <span asp-validation-for="PlaceCode" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Description" class="control-label labelStyle"></label>
            <textarea asp-for="Description" class="form-control"  style="margin-right: 10px; font-size: 17px;" ></textarea>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Price" class="control-label labelStyle"></label>
            <input asp-for="Price" class="form-control"  style="margin-right: 10px; font-size: 17px;"  />
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>
        <div class="form-groupM">
            <div class="containerM" style="color: #dbd8d8">
                @Html.DisplayNameFor(model => model.IsActive)
                <input type="checkbox" asp-for="IsActive" >
                <span class="checkmark"> </span><i class="fa fa-check check-btn" ></i>
            </div>
        </div>
        <div class="form-group">
            <input type="submit" value="ایجاد" class="btn btn-orange" style="width: 20%;margin-right: 40%;" />
        </div>
    </form>
</div>
 

 

soft98/Areas/Admin/Views/Banner/Delete.cshtml
@{
    Layout = null;
    var id= ViewBag.catId;
}

<form  asp-action="Delete" method="post" >
    <div asp-validation-summary="ModelOnly" class="text-center"></div>
    <div class="form-group" style="margin-bottom: 80px !important;">
        <h3 style="color: black;" class="text-center"> آیا از حذف اطمینان دارید؟</h3>
    </div>
    <div class="form-group">
        <input type="submit" class="btn-orangeM pull-right" value="تایید" style="border: none; top: -45px !important;" />
        <a  asp-action="Index"  asp-controller="Banner" class="btn-orangeM pull-left" style=" top: -45px !important;">بازگشت</a>
    </div>
</form>

soft98/Areas/Admin/Views/Banner/Details.cshtml
@model soft98.DataAccessLayer.Entities.Banner

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12
     col-sm-offset-0 col-xs-12 col-xs-offset-0" style="margin-top: 50px;">
    <h3 class="pull-right title-h">جزئیات بنر</h3>
    <h3 class="pull-left">
        <a asp-action="Create" class="btn-orange">ایجاد بنر</a>
    </h3>
</div>
<div class="clearfix"></div>
<br />

<div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12
     col-sm-offset-0 col-xs-12 col-xs-offset-0" style="margin-right: -135px;">
    <dl class="dl-horizontal table-chart-detail">
        <dt>
            @Html.DisplayNameFor(model => model.PlaceCode)
        </dt>
        <dd class="text-center">
            @Html.DisplayFor(model => model.PlaceCode)
        </dd>
        <hr />
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="text-center">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <hr />
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="text-center">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <hr />
        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>
        <dd class="text-center">
            @Html.DisplayFor(model => model.IsActive)
        </dd>
    </dl>
</div>
<div style="display: inline-block; margin-right:260px " class="btn-wrapp">
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn-orange">تغییر بنر</a> |
    <a asp-action="Index" class="btn-orange">بازگشت</a>
</div>

soft98/Areas/Admin/Views/Banner/Edit.cshtml
@model soft98.DataAccessLayer.Entities.Banner

@{
    ViewData["Title"] = "تغییر بنر";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12
     col-sm-offset-0 col-xs-12 col-xs-offset-0" style="margin-top: 50px;">
    <h3 class="pull-right title-h">تغییر بنر</h3>
    <h3 class="pull-left">
        <a asp-action="Index" class="btn-orange">بازگشت</a>
    </h3>
</div>
<div class="clearfix"></div>
<br />

<div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12
     col-sm-offset-0 col-xs-12 col-xs-offset-0">
    <form asp-action="Edit" class="table-chart">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label asp-for="PlaceCode" class="control-label labelStyle"></label>
            <input asp-for="PlaceCode" class="form-control"  style="margin-right: 10px; font-size: 17px;" />
            <span asp-validation-for="PlaceCode" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Description" class="control-label labelStyle"></label>
            <textarea asp-for="Description" class="form-control"  style="margin-right: 10px; font-size: 17px;"></textarea>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Price" class="control-label labelStyle"></label>
            <input asp-for="Price" class="form-control"  style="margin-right: 10px; font-size: 17px;" />
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>
        <div class="form-groupM">
            <div class="containerM" style="color: #dbd8d8">
                @Html.DisplayNameFor(model => model.IsActive)
                <input type="checkbox" asp-for="IsActive">
                <span class="checkmark"> </span><i class="fa fa-check check-btn"></i>
            </div>
        </div>
        <div class="form-group">
            <input type="submit"  value="اعمال تغییرات" class="btn btn-orange" style="width: 20%;margin-right: 40%;" />
        </div>
    </form>
</div>
 

soft98/Areas/Admin/Views/Banner/Index.cshtml
@model IEnumerable<soft98.DataAccessLayer.Entities.Banner>

@{
    ViewData["Title"] = "نمایش بنر ها";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12
     col-sm-offset-0 col-xs-12 col-xs-offset-0" style="margin-top: 50px;">
    <h3 class="pull-right title-h">نمایش بنر ها</h3>
    <h3 class="pull-left">
        <a asp-action="Create" class="btn-orange">ایجاد بنر </a>
    </h3>
</div>
<div class="clearfix"></div>
<br />

<div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12
     col-sm-offset-0 col-xs-12 col-xs-offset-0" style="margin-right: -135px;">
    <table class="table table-chart-matlab">
        <thead>
            <tr>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.PlaceCode)
                </th>

                <th class="text-center">
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.IsActive)
                </th>
                <th class="text-center"> عملیات</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-center">
                        @Html.DisplayFor(modelItem => item.PlaceCode)
                    </td>
                    <td class="text-center">
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td class="text-center">
                        @Html.DisplayFor(modelItem => item.IsActive)
                    </td>
                    <td class="text-left">
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn-xs btn-warning">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id" class="btn-xs btn-info">Details</a> |
                        <a href="#" onclick="Delete(@item.Id)" class="btn-xs btn-danger">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>


<div id="myModal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="bodymodal" class="modal-body">

            </div>
        </div>

    </div>
</div>

<script>
    function Delete(id) {
        $.ajax({
            url: "/Admin/Banner/Delete/" + id ,
            type: "Get",
            data: {}
        }).done(function (result) {
            $('#myModal').modal('show');
            $('#myModalHeader').html('');
            $('#bodymodal').html(result);
        });
    }
</script>